apiVersion: secrets-store.csi.k8s.com/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   # accepted provider options: azure or vault
  parameters:
    usePodIdentity: "false"         # [OPTIONAL for Azure] if not provided, will default to "false"
    keyvaultName: "akv-cbio"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: db-password
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: my-very-secret
          objectType: secret
          objectVersion: ""
    resourceGroup: "php"            # the resource group of the KeyVault
    subscriptionId: ""         # the subscription ID of the KeyVault
    tenantId: ""                 # the tenant ID of the KeyVault