apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-secrets-store
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: secrets-store.csi.k8s.com
    readOnly: true
    volumeHandle: kv
    volumeAttributes:
      providerName: "azure"
      usePodIdentity: "false"         # [OPTIONAL] default to "false" if empty
      keyvaultName: "akv-cbio"          # the name of the KeyVault
      objects:  |
        array:
          - |
            objectName: db-password
            objectType: secret        # object types: secret, key or cert
            objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
          - |
            objectName: my-very-secret
            objectType: secret
            objectVersion: ""
      resourceGroup: "php"            # the resource group of the KeyVault
      subscriptionId: ""         # the subscription ID of the KeyVault
      tenantId: ""                 # the tenant ID of the KeyVault
      cloudName: ""                   # [OPTIONAL] if not provided, will default to AzurePublicCloud
    nodePublishSecretRef:
      name: kvcreds
      namespace: default